[package]
name = "google-idtoken"
version = "0.1.0"
edition = "2021"

[features]
default = ["async"]
async = ["tokio"]
blocking = []

[dependencies]
openidconnect = "2.3.2"
tokio = { version = "1.19.2", features = ["full"], optional = true }
